language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-all-dev
      - cmake
script: 
- mkdir build
- cd build
- cmake ..
- make
- make test

